@host = http://localhost:3000
# @host = https://api.pitbot.fun
// get
POST {{host}}/order HTTP/1.1
content-type: application/json

{
  "customerId": "fcf1b5f5-b719-4925-b2ae-c1cf7fc230b3",
  "items": [{ "quantity": 3, "productId": "b3370d69-ff33-455f-9fdb-73c198548e03" }]
}

###

// get
GET {{host}}/order HTTP/1.1
x-auth-token: aa6eefe454bdd0d45c3be53fec20c605cefdcfbef434e61419e12ee8114e1d9a

"40-645"
